name: "commit's maker"
on:
  schedule:
  - cron: "57 22 * * *"

jobs:
  Commiter-job:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup git config
      run: |
        git config --local user.name ${{ secrets.USER_NAME }}
        git config --local user.email ${{ secrets.USER_EMAIL }}

    - name: Run script file
      run: |
         chmod +x ./commiter.sh
         ./commiter.sh
      shell: bash


