name: "commit's maker"
on:
  schedule:
  - cron: "0 7 * * *"

jobs:
  Commiter-job:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup git config
      run: |
        git config user.name ${{USER_NAME}}
        git config user.email ${{USER_EMAIL}}

    - name: Run script file
      run: |
         chmod +x ./commiter.sh
         ./commiter.sh
      shell: bash


